server:
  port: 8081
  servlet:
    session:
      timeout: 120m
    context-path: /hz/
         # HTTP ENCODING

debug: true
spring:
  profiles:
    active: base,freemark,mybatis
#邮件

  mail:
    host: smtp.exmail.qq.com
    username: cszs@xt12345.org
    password: 68YGwQV76KaUn9Lp
    properties:
      mail:
        self:
          username: momo
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          auth: true
          starttls:
            enable: true
            required: true

#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false
#    mode: LEGACYHTML5

  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1000MB


#  session:
#      store-type: none





logging:
  config: classpath:logback.xml
  path: logs
  level:
    org:
      springframework:
         security: INFO

#spring.mvc.static-path-pattern=/static/**
#logging.level.org.springframework.security = debug
#logging.level.org.springframework.security.web = warn
#logging.level.org.springframework.web = warn


